{{- if .Values.backend.enabled }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.database.svc.cluster.local:5432/unimind

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"

{{- end }}
