{{- if .Values.backend.enabled }}

apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080

  type: ClusterIP

{{- end }}
